robotpy/examples

getting-started/robot.py

This removes the deprecated LiveWindow.run() usage, as per [this allwpilib example](https://github.com/wpilibsuite/allwpilib/blob/0ef9803363380c58804a0d885a7cc7ea8233a1ac/wpilibcExamples/src/main/cpp/examples/GearsBot/src/Robot.cpp), the new `arcadeDrive` syntax as per [this allwpilib example](https://github.com/wpilibsuite/allwpilib/blob/master/wpilibcExamples/src/main/cpp/examples/ArcadeDrive/src/Robot.cpp), and uses the new `DifferentialDrive` class instead of the deprecated `RobotDrive`.
Note that this removes parity with the ScreenSteps documentation, since it has not yet been updated for both C++ and Java. I've already sent an email about this.
I'm also just about finished with updating the drivetrain sections of the Anatomy of a Robot page from the Programmer's Guide.

Update getting-started example to use new drive paradigm

---

physics/src/robot.py

Hello,
Thank you for the work on the sim.  When I tried the auto, the simulator crashed because it could not find the robot_drive method.  So, I edited it to mimic that of teleop.  This new physics module is incredible.

Removed robot_drive from Auto.

---

mecanum-drive/robot.py

As stated in the #49 issue in the base repository, we need example code that matches WPIlib examples closely.
I may have broken some PEP guidelines, but I believe we need formatting to be in line with C++/Java examples.
The code has been tested in simulation only, because my team does not have any SparkMax motor controllers.

Edited the mecanum drive example code to be more frc-docs like.

---

addressableled/robot.py
run_tests.sh

Issue #49 requests some WPILib examples adapted from Java.
I am adding the Addressable LED class example here.
The code has been tested only in the simulator only, and the results were:

Adding Addressabled LED class example

---

mechanism2d/robot.py
run_tests.sh

The title is pretty much self explanatory. I didn't need a physics.py file to test it since the simulation GUI takes care of encoders and analog inputs.
#49

Added mechanism2d example.

---

commands-v2/armbotoffboard/examplesmartmotorcontroller.py
elevator-trapezoid-profile/examplesmartmotorcontroller.py
elevator-trapezoid-profile/robot.py
run_tests.sh

Add elevator trapezoid profile example

---

getting-started/robot.py

#49
The example has already been completed, but the `right_motor` wasn't inverted.

Set inverted of right motor to true

---

commands-v2/armbot/constants.py
commands-v2/armbot/robot.py
commands-v2/armbot/robotcontainer.py
commands-v2/armbot/subsystems/armsubsystem.py
commands-v2/armbot/subsystems/drivesubsystem.py
run_tests.sh

Following #49
In `constants.py` file, the constants are grouped in different classes (I don't know if this style will respect the [RobotPy's porting guide](https://github.com/robotpy/examples/blob/main/CONTRIBUTING.md)).
In `robotcontainer.py`, I created a function named `moveArm`, to adapt in a single line (two calls in `configureButtonBindings`).

Add armbot example

---

relay/robot.py
run_tests.sh

I haven't added code to another person's repository before, so I am trying to start small. I saw the request for more examples and tried to pick the easiest thing I could. Probably not a super helpful example, but if I can do this well, I will try to pick off more important stuff later.

Added relay example.

---

arcade-drive-xbox-controller/robot.py
run_tests.sh

I added comments to match [the cpp example](https://github.com/wpilibsuite/allwpilib/blob/main/wpilibcExamples/src/main/cpp/examples/ArcadeDriveXboxController/cpp/Robot.cpp).  Let me know if you'd rather it be a little simpler like the existing arcade-drive example.
Confirmed it runs in sim

add arcade-drive-xbox-controller example

---

run_tests.sh
tank-drive-xbox-controller/robot.py

I cloned the existing tank-drive example then modified it to match [the cpp example](https://github.com/wpilibsuite/allwpilib/blob/main/wpilibcExamples/src/main/cpp/examples/TankDriveXboxController/cpp/Robot.cpp).
Confirmed it runs in sim

add tank-drive-xbox-controller example

---

run_tests.sh
ultrasonic/robot.py

I based this on the java example, but the java Ultrasonic class seems to have some methods that are not in the robotpy, at least not according to the most recent documentation. Therefore I am not using the methods `getRangeMM` and `getRangeInches`, but instead show using `getRange`. If you would like me to do the conversions I can do that.

Created Ultrasonic example

---

arcade-drive-xbox-controller/robot.py
arcade-drive/robot.py
canpdp/robot.py
digital-communication/robot.py
dutycycle-encoder/robot.py
dutycycle-input/robot.py
encoder/robot.py
flywheel-bangbang-controller/physics.py
flywheel-bangbang-controller/robot.py
gyro-mecanum/robot.py
gyro/robot.py
hid-rumble/robot.py
motor-control/robot.py
potentiometer-pid/robot.py
quick-vision/robot.py
ramsete-controller/drivetrain.py
ramsete-controller/robot.py
relay/robot.py
run_tests.sh
tank-drive-xbox-controller/robot.py
tank-drive/robot.py

Some new examples:
- digital-communication
- dutycycle-encoder
- dutycycle-input
- encoder
- flywheel-bangbang-controller
- gyro-mecanum
- hid-rumble
- quick-vision
- ramsete-controller
Also reformated/updated a few existing ones to be more consistent with java examples

low hanging fruit

---

mecanum-bot/drivetrain.py
mecanum-bot/robot.py
run_tests.sh

wpimath.kinematics.ChassisSpeeds.descretize(...) doesn't seem to exist.  Am I missing it somewhere? Is it new and needs to be added? Is there a different/better approach?
RobotPy docs: https://robotpy.readthedocs.io/projects/wpimath/en/latest/wpimath.kinematics/ChassisSpeeds.html
wpilibj source: https://github.com/wpilibsuite/allwpilib/blob/main/wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java#L92

Add mecanum-bot example

---

CONTRIBUTING.md

An added sub-point to go within the contribution guide based on the automated workflow. It specifies that the line `#!/usr/bin/env python3` should be at the beginning of all `robot.py` file but not other files.

Clarification within CONTRIBUTING.md

---

AprilTagsVision/Robot.py
AprilTagsVision/robot.py
AprilTagsVision/vision.py
run_tests.sh

This is the rebased and updated 2024 version of #100
The following image is the test I ran of the vision.py file:

[Rebase] add AprilTagVision example

---

AxisCamera/robot.py
AxisCamera/vision.py
run_tests.sh

Addresses issue #49 [Axis Camera Sample](https://github.com/wpilibsuite/allwpilib/tree/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/axiscamera) necessity! Could someone with a rio test the Axis Camera code because, I do not have a rio or an axis camera currently.

Add AxisCamera sample

---

SwerveBot/swervemodule.py

The previous implementation of the SwerveModule class getPosition method took the rate of the drive encoder (corresponding to velocity) instead of its distance. I changed it to use the distance instead.
The java implementation using distance is [here](https://github.com/wpilibsuite/allwpilib/blob/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/SwerveModule.java)

Changed the swervemodule getPosition function to use encoder distance

---

XrpReference/commands/arcadedrive.py
XrpReference/commands/autonomous_distance.py
XrpReference/commands/autonomous_time.py
XrpReference/commands/drivedistance.py
XrpReference/commands/drivetime.py
XrpReference/commands/turndegrees.py
XrpReference/commands/turntime.py
XrpReference/robot.py
XrpReference/robotcontainer.py
XrpReference/subsystems/arm.py
XrpReference/subsystems/drivetrain.py
run_tests.sh

Add XrpReference example

---

.github/workflows/test.yml
.pre-commit-config.yaml

This intends to do two things:
1. Pin the black version, so we don't get surprised by the annual black major release suddenly failing CI.
2. Make it easier for first-time contributors to discover the formatters/linters we have, and make these checks easier to reproduce locally (e.g. `pre-commit run --all-files`).

Add pre-commit config

---

ArmBot/subsystems/drivesubsystem.py
ArmBotOffboard/subsystems/drivesubsystem.py
DifferentialDriveBot/drivetrain.py
FrisbeeBot/subsystems/drivesubsystem.py
GyroDriveCommands/subsystems/drivesubsystem.py
HatchbotInlined/subsystems/drivesubsystem.py
HatchbotTraditional/subsystems/drivesubsystem.py
RamseteCommand/subsystems/driveSubsystem.py
RamseteController/drivetrain.py

Based on https://github.com/wpilibsuite/allwpilib/pull/6053, I updated the following examples:
- Armbot
- ArmBotOffboard
- DifferentialDriveBot
- GyroDriveCommands
- FrisbeeBot
- HatchbotInlined
- HatchbotTraditional
- RamseteCommand
- RamseteController
These are all of the available examples from said PR that could be updated
Please let me know if you would like any changes.

Update examples using MotorControllerGroup
